### ISSUE TITLE
Ensure sequence numbers are never reused

### ISSUE THREAD

**Issue by fregante** [pixiebrix/webext-messenger#207]
https://github.com/pixiebrix/webext-messenger/blob/597e2fc72632c8c579977ff59687030f21cf8914/source/sender.ts#L192-L193

Two calls in the same millisecond will have the same `seq`

I don’t think there was a specific reason to use the time, so I'll just use a global `seq++` counter ("global" but per-context)

Seen in https://github.com/pixiebrix/pixiebrix-extension/issues/6443#issuecomment-1933411095

**Comment by twschiller** [comment]
> Two calls in the same millisecond will have the same seq

It is potentially more frequent than that if the browser is cutting off granularity for privacy reasons. 

> I don’t think there was a specific reason to use the time

Conceptually, the benefit of using time is that it's monotonically increasing across all senders. That allows you to order messages across senders if needed. In practice, though, as we did for the extension, you still need a per-sender counter to avoid generating the same sequence number multiple times

**Comment by fregante** [comment]
Yes the counter here is used exclusively to distinguish calls for logging and it repeats every 100 seconds. It's less of a "sequence" and more of an "approximate temporary identifier".
