### ISSUE TITLE
Allow discarding messages 

### ISSUE THREAD

**Issue by fregante** [pixiebrix/webext-messenger#38]
In some rare cases, only the latest version of a message is useful, so it's not important to preserve messages that are currently being retried.

## Concerns

- This might be a micro-optimization, depending on the amount of expected messages that will be sent while a target isn't ready
- The retry logic is handled by `p-retry` and it might not be easy to check whether a message is currently in queue. Maybe an [AbortSignal](https://github.com/sindresorhus/p-retry/issues/53) could be used to automatically cancel any messages in queue

## Prior art

Discarding logic:

https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/actionPanel/native.tsx#L167:L167

Used as a notification only:

https://github.com/pixiebrix/pixiebrix-extension/blob/ea335a13e28a8c63ab1c73a6e4c2c2ba27a65da9/src/background/browserAction.ts#L150-L158

**Comment by twschiller** [comment]
I would put this as low priority — I haven't seen the overhead for the only current usage have any impact on performance
