### ISSUE TITLE
"No handler registered for # in the receiving end" is not quite right for named targets

### ISSUE THREAD

**Issue by fregante** [pixiebrix/webext-messenger#78]
1. Double-click the browser action button in PixieBrix
2. See error in background page

The error is caused by:

```js
await pingSidebar({ tabId: "this", page: "/sidebar.html" });
```

The target doesn't existing long enough to respond, or rather "it never existed," so the message should be along the lines of "target not found" rather than "no handlers registered."

## Quick refresher

This message is sent once via `browser.runtime.sendMessage` and is received by every open `chrome://` page and background, which decides whether to answer or ignore.

## Resolution

- Case: target doesn't exist or didn't call `chrome.runtime.onMessage.addListener`
	- Browser throws: `Could not establish connection. Receiving end does not exist.`
		- Sender should throw: `Target could not be found`
- Case: target didn't call `registerMethods`
	- Receiver should throw: [`No handlers registered in [target]`](https://github.com/pixiebrix/webext-messenger/pull/77/files)
	- Sender should retry
- Case: target didn't register requested method
	- Receiver should throw: `No handler registered for # in [target]` 

## Notes

The current retrier does not remember errors. If the first call returns "No handlers registered" and the second error is "Target could not be found". This is particularly troublesome because only the last error ever surfaces.

In this case, it should probably stop retrying because the target was found but is now gone.

## Related

This issue is somewhat related to a recent one, but it has a completely different cause:

- https://github.com/pixiebrix/webext-messenger/issues/74

**Comment by fregante** [comment]
I've been wondering if we should move to a more stateful approach — if we can at all.

The Messenger has been built around two core concepts:

- messaging opaqueness: call a function at an address (target), hide the transport protocol
- automatic retrying for missing and "unready" targets

The first part makes the communication stateless and independent, which means that the caller doesn't need to know much about the target and its life cycle (blessing and a curse).

The second part appears to be incredibly complicated and variable, which is why we've been tweaking it ever since.

---

Thinking out loud:

There are a few possible solutions to this, with varying degrees of complexity (none of this grants us bug armistice)

- `runtime.connect()`: 
	- retry only the connection, connect once, reuse connection, know when the target is gone
	- ok, what happens when it closes? We must reopen if it's a background page, but we never try again for `{target: "this", page: "sidebar.html"}`? Doesn't seem like a direct solution to all
- `webNavigation` API:
	- track and find frame IDs, then use a more exact `chrome.tabs.sendMessage(tab, frame)` message instead of named targets
	- this helps, but seems complex when it's time to retry on a new sidebar in the same tab for example
- move target tracking to the user side:
	- expose a stateful `obtainTarget({tab: 1})` API, then use it in the following communication, as `openSidebar(target)` and `closeSidebar(target)`. Once the target is closed, it's gone, and you need a new target
	- this forces the user to have to keep track of these targets internally and having to know when to attempt to obtain a new target

---


This feels like we're going to increase complexity exponentially and makes me long for a more straightforward approach instead. I'd love to be able to drop retrying and moving at least that part to the user side via internal API, like:


```js
const sidebar = {target: "this", page: "sidebar.html"};
await messenger.expectTarget(sidebar); // Pings until it connects

await showPanel(sidebar); // Never retries
await updatePanel(sidebar); // Never retries
```

If the methods fail, they fail, the target is gone, we deal with it in the application as usual. I think this helps to give us control over when the trying happens "per target" instead of "per function call".

At any given time, we kind of know whether a target should exist or "will open soon". `expectTarget` in this case would also replace a user land `PING_SIDEBAR` method and other similar methods we have. It would probably help us emit more exact errors.

**Comment by twschiller** [comment]
> I've been wondering if we should move to a more stateful approach — if we can at all.

Will take a look at this more this evening. At first glance, the proposal is reinventing ports a bit: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/connect

**Comment by fregante** [comment]
Did you paste the wrong link?

**Comment by fregante** [comment]
I mentioned that in the same comment. The problem with that is that either:

- the user has to manually connect and hold onto the `port` explicitly, bringing this complexity back into the app (my third point), or
- if we don't change the API, it means we still need to attempt to connect every time a `target` is messaged but no open `port`s are found.

`runtime.connect` _might_ be useful, but we still need to know how to adapt the messenger API/behavior around it. Just replacing `runtime.sendMessage` doesn't solve these issues.
