### ISSUE TITLE
Remove branch protection from repo

### ISSUE THREAD

**Issue by fregante** [pixiebrix/webext-messenger#87]
Opening an issue to keep track of the conversation.

Re: https://github.com/pixiebrix/webext-messenger/commit/24192c07d131f1714992e41d43a2c970d18b2daa#commitcomment-82700570

> For our upcoming SOC-2 (security audit) we need to enable branch protections on any code that we publish

We don't publish `webext-messenger` directly to consumers, it's an npm dependency that is covered by the branch protections included in the extension itself. Adding a branch protection here is akin to requiring that every one of our npm dependencies must also be protected by us.

For that reason I don’t think we need to have branch protection here (also for your own ease of update)

**Comment by twschiller** [comment]
@johnnymetz is it possible to mark a single repo as out of scope?

**Comment by fregante** [comment]
Ping. The publishing step fails due to the protections:

<img width="721" alt="Screenshot" src="https://github.com/user-attachments/assets/76d5a4a2-39ac-438e-9779-f61fb5bcb4e3">

**Comment by grahamlangford** [comment]
Should be fixed now

**Comment by fregante** [comment]
Confirmed

https://github.com/pixiebrix/webext-messenger/actions/runs/12155436351/job/33896988124
https://github.com/pixiebrix/webext-messenger/releases/tag/v0.29.1
